name: Deploy to GitHub Pages
# on:
#   push:	
#     branches:	
#       - master
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      type:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Release Type'
        # Default value if no value is explicitly provided
        default: 'Web'
        # Input has to be provided for the workflow to run
        required: false

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
        # flutter-version: '2.0.5'
    - run: flutter pub get
    # - run: flutter test
    - run: flutter build -v web --release
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: tg21.github.io
        BRANCH: master
        FOLDER: build/web/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
